### ISSUE TITLE
Sent emails are not including the siteurl

### ISSUE THREAD

**Issue by sunscreem** [mediabeastnz/craft-commerce-abandoned-cart#12]
All up and running in production, but a strange bug is happening now.

The siteurl isn't being pre-pended to the button url in some of the emails.

I've had a couple of test emails through and the button has included the site url no-problem, but I just raised another test and sure enough the actual url generated in the template ended up being:

```
"abandoned-cart-restore/?number=97738abedf6138b999c4c7e1e5a90dfa"
```

I'm just debugging now, but wanted to quickly create the issue incase it was something that made you go "oh - I know exactly what's causing that..."

**Comment by mediabeastnz** [comment]
Hey @sunscreem, good to hear you're up and running!

Are you using the default templates or your own custom ones?
The default templates use this to build the link `{{ siteUrl ~ checkoutLink }}`

`siteUrl` is a global variable in Craft so that should provide a full URL (https://example.com), specially when in production.

**Comment by sunscreem** [comment]
Urgh @mediabeastnz - it was at my end. 

Ignore alllllll of this.
