### ISSUE TITLE
Empty cart mails are sent

### ISSUE THREAD

**Issue by WHITE-developer** [mediabeastnz/craft-commerce-abandoned-cart#44]
Hello,

We've used your plugin in some of our projects. In two of them we received messages from customers complaining about empty mails. So a cart without any products, like this:

![image](https://user-images.githubusercontent.com/22771556/93063910-34775b80-f677-11ea-851b-8cc52eee6e9f.png)

I see there is a check for totalPrice before sending, but it looks like this isn't working as we should expect. Any ideas on this?

Thanks.

**Comment by mediabeastnz** [comment]
Hey @WHITE-developer yeah there are a few checks in place way before the email is sent e.g. 
- totalPrice > 0
- isCompleted = 0
- email != ""

I could however strengthen this by double check these just before an email is sent.

**Comment by WHITE-developer** [comment]
Hi, I'm not sure why this happens sometimes. Would be great to do extra check.

Maybe it has something to do with purchasables that are not available anymore or something like that, it that possible?

**Comment by samhibberd** [comment]
Hi @mediabeastnz, this is something that could be improved for sure.

I think it's caused by a cart getting recalculated when saved before sending, at this point any line items that are no longer available would get removed from the cart and a notice will get added (same goes for any price changes).

https://github.com/mediabeastnz/craft-commerce-abandoned-cart/blob/aed73d7ad5d29e435d6bf9a0d54f124dbfd034fc/src/jobs/SendEmailReminder.php#L57

We think this is the correct behaviour, we don't want to notify people about items that are no longer available.

So I think the only thing that needs to be added is a check at the point of sending (in the queue job or sendMail) to prevent any send if `!$cart->hasLineItems()`

**Comment by mediabeastnz** [comment]
I'll look to release the update over the next couple days

**Comment by antcooper** [comment]
+1 Our client has mentioned that some empty emails have been sent too.

**Comment by WHITE-developer** [comment]
Any news on this one? 

We still have customers complaining about empty mails. Would be nice if the suggested solution could be implemented.

**Comment by WHITE-developer** [comment]
Can you please have a look at our PR, so this can be fixed/

Thanks.
