### ISSUE TITLE
What was the reason to remove the stats and widgets?

### ISSUE THREAD

**Issue by terryupton** [mediabeastnz/craft-commerce-abandoned-cart#84]
### Question

In v3.0.0
Removed "Abandoned Carts Total" widget.
Removed stats from Abandoned Carts Dashboard

I just wandered what the intention was behind this @engram-design ?
Not that it is a great loss, but I wondered the intentions here? Also would give me some context for informing clients about this change.

**Comment by engram-design** [comment]
Mostly because they're buggy (throwing errors or just incorrect values), and because I'm planning to revamp it to some proper reporting that's a bit more flexible and hopefully useful.

I know that's probably an unexpected change (hence the major version), but certainly looking to add back more reporting stats, and any feedback is welcome towards that. A few people have already put forward their suggestions on how this might look.

**Comment by terryupton** [comment]
Thanks Josh. I thought that might be the case. 
Looking forward to what's to come for Abandoned Cart.
